export enum UserPermissionsEnum {
  READ_USERS = "READ_USERS",
  UPDATE_USERS = "UPDATE_USERS",
  CREATE_USERS = "CREATE_USERS",
  DELETE_USERS = "DELETE_USERS",
}

export enum StaticPermissionsEnum {
  READ_STATICS = "READ_STATICS",
  UPDATE_STATICS = "UPDATE_STATICS",
  CREATE_STATICS = "CREATE_STATICS",
  DELETE_STATICS = "DELETE_STATICS",
}

export enum ContactMessagePermissionsEnum {
  READ_CONTACT_MESSAGES = "READ_CONTACT_MESSAGES",
  UPDATE_CONTACT_MESSAGES = "UPDATE_CONTACT_MESSAGES",
  CREATE_CONTACT_MESSAGES = "CREATE_CONTACT_MESSAGES",
  DELETE_CONTACT_MESSAGES = "DELETE_CONTACT_MESSAGES",
}

export enum ArtPermissionsEnum {
  READ_ARTS = "READ_ARTS",
  UPDATE_ARTS = "UPDATE_ARTS",
  CREATE_ARTS = "CREATE_ARTS",
  DELETE_ARTS = "DELETE_ARTS",
}

export enum CategoryPermissionsEnum {
  READ_CATEGORIES = "READ_CATEGORIES",
  UPDATE_CATEGORIES = "UPDATE_CATEGORIES",
  CREATE_CATEGORIES = "CREATE_CATEGORIES",
  DELETE_CATEGORIES = "DELETE_CATEGORIES",
}

export enum SubCategoryPermissionsEnum {
  READ_SUBCATEGORIES = "READ_SUBCATEGORIES",
  UPDATE_SUBCATEGORIES = "UPDATE_SUBCATEGORIES",
  CREATE_SUBCATEGORIES = "CREATE_SUBCATEGORIES",
  DELETE_SUBCATEGORIES = "DELETE_SUBCATEGORIES",
}

export enum DesignerPermissionsEnum {
  READ_DESIGNERS = "READ_DESIGNERS",
  UPDATE_DESIGNERS = "UPDATE_DESIGNERS",
  CREATE_DESIGNERS = "CREATE_DESIGNERS",
  DELETE_DESIGNERS = "DELETE_DESIGNERS",
}

export enum OptionPermissionsEnum {
  READ_OPTIONS = "READ_OPTIONS",
  UPDATE_OPTIONS = "UPDATE_OPTIONS",
  CREATE_OPTIONS = "CREATE_OPTIONS",
  DELETE_OPTIONS = "DELETE_OPTIONS",
}

export enum ProductPermissionsEnum {
  READ_PRODUCTS = "READ_PRODUCTS",
  UPDATE_PRODUCTS = "UPDATE_PRODUCTS",
  CREATE_PRODUCTS = "CREATE_PRODUCTS",
  DELETE_PRODUCTS = "DELETE_PRODUCTS",
}

export enum ReviewPermissionsEnum {
  READ_REVIEWS = "READ_REVIEWS",
  UPDATE_REVIEWS = "UPDATE_REVIEWS",
  CREATE_REVIEWS = "CREATE_REVIEWS",
  DELETE_REVIEWS = "DELETE_REVIEWS",
}

export enum VendorPermissionsEnum {
  READ_VENDORS = "READ_VENDORS",
  UPDATE_VENDORS = "UPDATE_VENDORS",
  CREATE_VENDORS = "CREATE_VENDORS",
  DELETE_VENDORS = "DELETE_VENDORS",
}

export enum MockupPermissionsEnum {
  READ_MOCKUPS = "READ_MOCKUPS",
  UPDATE_MOCKUPS = "UPDATE_MOCKUPS",
  CREATE_MOCKUPS = "CREATE_MOCKUPS",
  DELETE_MOCKUPS = "DELETE_MOCKUPS",
}

export enum RolePermissionsEnum {
  READ_ROLES = "READ_ROLES",
  UPDATE_ROLES = "UPDATE_ROLES",
}

export enum NewsletterPermissionsEnum {
  READ_NEWSLETTER = "READ_NEWSLETTER",
}
